server:
  port: 8080
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ChipData?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
      username: root
      password: 1233456
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          temp:
            use_jdbc_metadata_defaults: false